from brdocvalidator.validation import check_email
from brdocvalidator.validation import check_cpf
from brdocvalidator.validation import check_doc
from brdocvalidator.validation import check_cnpj
from brdocvalidator.validation import check_cpf
from brdocvalidator.validation import check_birth_date
from brdocvalidator.validation import encodePass
from brdocvalidator.validation import comparePass